### ISSUE TITLE
Plistutil calls in device.rb should cache results

### ISSUE THREAD

**Issue by jonpwilson** [bbc/device_api-ios#10]
Similar to how the device properties are stored, though we will need to check that it's the properties for the same app when called.

**Comment by jrmhaig** [comment]
@jonpwilson Is this still required with Hive Mind?

**Comment by jonpwilson** [comment]
This is still required, but it is now in the wrong place. The plistutil code was moved into Fruity Builder and so I'll re-raise this issue there
