### ISSUE TITLE
Missing Repository

### ISSUE THREAD

**Issue by newtewt** [bbc/device_api-ios#28]
Hey, I'm trying to use DeviceAPI::IOS::IPAddress class but it errors with 'IP Address package not installed: Please see https://github.com/bbc/ios-test-helper' but the github repository doesn't exist. This would be helpful if it exists.

**Comment by jitgo** [comment]
Hi @newtewt 

We're currently testing a new ways to deploy our iOS tests so unfortunately this method is out of date. Hopefully we will have this out soon.
